# Generated by Django 4.1.1 on 2022-12-25 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PATIENT', '0005_multipleuploadimages_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='medical',
            new_name='usern',
        ),
    ]
