# Generated by Django 4.1.1 on 2023-01-03 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PATIENT', '0006_rename_medical_patient_usern'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='age',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
