# Generated by Django 4.1.5 on 2023-01-12 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PATIENT', '0007_alter_patient_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='username',
        ),
    ]
