# Generated by Django 4.1.5 on 2023-01-15 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PATIENT', '0008_remove_patient_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagesUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('images', models.ImageField(null=True, upload_to='images')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PATIENT.patient')),
            ],
        ),
    ]
