# Generated by Django 4.1.5 on 2023-01-15 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PATIENT', '0009_imagesupload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagesupload',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
