# Generated by Django 4.1.5 on 2023-01-22 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PATIENT', '0010_alter_imagesupload_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='patient_images',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='patient',
            name='prescrip_images',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
