# Generated by Django 4.1.5 on 2023-01-23 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PATIENT', '0012_prescriptionoldupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='flag',
            field=models.BooleanField(default=True),
        ),
    ]
