# Generated by Django 4.1.5 on 2023-01-25 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PATIENT', '0013_patient_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='blood',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
