# Generated by Django 4.1.5 on 2023-02-05 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PATIENT', '0014_alter_patient_blood'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='display_flag',
            field=models.BooleanField(default=False),
        ),
    ]
