# Generated by Django 4.2.3 on 2023-08-18 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PATIENT', '0018_patientimages'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='alternative_number',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AlterUniqueTogether(
            name='patient',
            unique_together={('phone', 'alternative_number')},
        ),
    ]
