# Generated by Django 4.2.3 on 2023-08-18 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PATIENT', '0019_patient_alternative_number_alter_patient_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='alternative_number',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
