# Generated by Django 4.2.3 on 2023-08-18 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PATIENT', '0020_alter_patient_alternative_number'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='patient',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone',
            field=models.CharField(default='', max_length=12, unique=True),
        ),
    ]
