# Generated by Django 4.2.3 on 2023-08-24 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PATIENT', '0021_alter_patient_unique_together_alter_patient_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='forget_password_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
