# Generated by Django 4.2.3 on 2023-11-10 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("PATIENT", "0022_patient_forget_password_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="phone",
            field=models.CharField(default="", max_length=12),
        ),
    ]
