# Generated by Django 4.2.3 on 2023-11-23 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("PATIENT", "0023_alter_patient_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="dietry_preference",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="patient",
            name="height",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="patient",
            name="marital_status",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="patient",
            name="occupation",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="patient",
            name="qualification",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="patient",
            name="referred_by",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="patient",
            name="weight",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
