# Generated by Django 4.2.3 on 2023-11-23 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("PATIENT", "0024_patient_dietry_preference_patient_height_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="diagnosis_final",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="patient",
            name="diagnosis_provisional",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
