# Generated by Django 4.1.1 on 2022-12-31 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('COMMON_APP', '0003_payment_delete_multipleimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='hr',
            name='branch',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='receptionist',
            name='branch',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
