# Generated by Django 4.1.5 on 2023-01-21 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('COMMON_APP', '0004_hr_branch_receptionist_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='flag',
            field=models.BooleanField(default=True),
        ),
    ]
