# Generated by Django 4.1.5 on 2023-01-21 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('COMMON_APP', '0005_prescription_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='durations',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='potency',
            field=models.CharField(max_length=50),
        ),
    ]
