# Generated by Django 4.1.5 on 2023-02-03 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('COMMON_APP', '0006_alter_prescription_durations_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='stat',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
