# Generated by Django 4.1.5 on 2023-02-05 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('COMMON_APP', '0007_appointment_stat'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='token',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
