# Generated by Django 4.1.5 on 2023-02-05 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('COMMON_APP', '0008_appointment_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='token1',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
