# Generated by Django 4.1.5 on 2023-02-05 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('COMMON_APP', '0009_appointment_token1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='token',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='token1',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
