# Generated by Django 4.1.5 on 2023-02-06 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('COMMON_APP', '0010_alter_appointment_token_alter_appointment_token1'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='diagnose',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='start_date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
