# Generated by Django 4.1.5 on 2023-02-06 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('COMMON_APP', '0011_prescription_diagnose_prescription_start_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
    ]
