# Generated by Django 4.1.5 on 2023-02-06 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('COMMON_APP', '0012_tokenupdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='tokenupdate',
            name='consultancy',
            field=models.BooleanField(default=False),
        ),
    ]
