# Generated by Django 4.1.5 on 2023-02-15 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('COMMON_APP', '0013_tokenupdate_consultancy'),
    ]

    operations = [
        migrations.AddField(
            model_name='hr',
            name='hr_image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
