# Generated by Django 4.1.5 on 2023-02-15 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('COMMON_APP', '0014_hr_hr_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='receptionist',
            name='recep_image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
