# Generated by Django 4.1.5 on 2023-02-15 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('COMMON_APP', '0016_receptionistdocs'),
    ]

    operations = [
        migrations.CreateModel(
            name='HRDocs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('images', models.ImageField(blank=True, null=True, upload_to='images')),
                ('hr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='COMMON_APP.hr')),
            ],
        ),
    ]
