# Generated by Django 4.1.7 on 2023-06-09 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('COMMON_APP', '0017_hrdocs'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='notification_flag',
            field=models.BooleanField(default=False),
        ),
    ]
