# Generated by Django 4.1.7 on 2023-06-10 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('COMMON_APP', '0018_appointment_notification_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='doctor_notification',
            field=models.BooleanField(default=False),
        ),
    ]
