# Generated by Django 4.2.3 on 2023-08-05 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PATIENT', '0017_newcasepaperupload'),
        ('COMMON_APP', '0023_ultrasonography'),
    ]

    operations = [
        migrations.CreateModel(
            name='UltrasonographyRecords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('records', models.CharField(blank=True, max_length=500, null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='PATIENT.patient')),
            ],
        ),
    ]
