# Generated by Django 4.2.3 on 2023-08-10 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('COMMON_APP', '0034_alter_ctscannewrecords_records_mriscannewrecords'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='medicine_flag',
            field=models.BooleanField(default=False),
        ),
    ]
