# Generated by Django 4.2.3 on 2023-08-11 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('COMMON_APP', '0035_appointment_medicine_flag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='investigationadvised',
            old_name='name',
            new_name='investigation_name',
        ),
        migrations.RenameField(
            model_name='ultrasonography',
            old_name='name',
            new_name='ultrasonography_name',
        ),
    ]
