# Generated by Django 4.2.3 on 2023-08-11 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('COMMON_APP', '0036_rename_name_investigationadvised_investigation_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='investigationadvised',
            old_name='investigation_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='ultrasonography',
            old_name='ultrasonography_name',
            new_name='name',
        ),
    ]
