# Generated by Django 4.2.3 on 2023-08-19 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PATIENT', '0021_alter_patient_unique_together_alter_patient_phone'),
        ('COMMON_APP', '0037_rename_investigation_name_investigationadvised_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherPrescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('other_price', models.CharField(blank=True, max_length=10, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PATIENT.patient')),
            ],
        ),
    ]
