# Generated by Django 4.2.3 on 2023-08-20 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('COMMON_APP', '0038_otherprescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='patient_new_old',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
