# Generated by Django 4.2.3 on 2023-08-23 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('COMMON_APP', '0039_appointment_patient_new_old'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='email_flag',
            field=models.BooleanField(default=False),
        ),
    ]
