# Generated by Django 4.2.3 on 2023-09-05 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('COMMON_APP', '0042_addconsultationcharges'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
