# Generated by Django 4.2.3 on 2023-09-05 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('COMMON_APP', '0043_stockname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_name', models.CharField(blank=True, max_length=50, null=True)),
                ('quantity', models.IntegerField(blank=True, default='0', null=True)),
                ('stock_unit', models.CharField(blank=True, choices=[('', 'Please Select Unit from list'), ('Kg', 'Kg'), ('Piece', 'Piece'), ('Packet', 'Packet'), ('Bottle', 'Bottle'), ('Box', 'Box')], max_length=50, null=True)),
                ('receive_quantity', models.IntegerField(blank=True, default='0', null=True)),
                ('issue_quantity', models.IntegerField(blank=True, default='0', null=True)),
                ('reorder_level', models.IntegerField(blank=True, default='0', null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('approval_flag_new', models.BooleanField(default=True)),
                ('approval_flag_issue', models.BooleanField(default=False)),
                ('approval_flag_receive', models.BooleanField(default=False)),
                ('stock_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='COMMON_APP.stockname')),
            ],
        ),
    ]
