# Generated by Django 4.2.3 on 2023-09-05 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('COMMON_APP', '0044_stock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='approval_flag_issue',
            new_name='approval_flag_update',
        ),
    ]
