# Generated by Django 4.2.3 on 2023-09-05 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('COMMON_APP', '0045_rename_approval_flag_issue_stock_approval_flag_update'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='approval_flag_update',
            new_name='approval_flag_updtate',
        ),
    ]
