# Generated by Django 4.2.4 on 2023-09-06 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('COMMON_APP', '0046_rename_approval_flag_update_stock_approval_flag_updtate'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddMedicineHR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='AddPotencyHR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('potency_name', models.CharField(max_length=30)),
            ],
        ),
    ]
