# Generated by Django 4.2.4 on 2023-09-06 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('COMMON_APP', '0047_addmedicinehr_addpotencyhr'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicineStockList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, default='0', null=True)),
                ('receive_quantity', models.IntegerField(blank=True, default='0', null=True)),
                ('issue_quantity', models.IntegerField(blank=True, default='0', null=True)),
                ('reorder_level', models.IntegerField(blank=True, default='0', null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('approval_flag_new', models.BooleanField(default=True)),
                ('approval_flag_updtate', models.BooleanField(default=False)),
                ('approval_flag_receive', models.BooleanField(default=False)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='COMMON_APP.addmedicinehr')),
                ('potency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='COMMON_APP.addpotencyhr')),
            ],
        ),
    ]
