# Generated by Django 4.2.4 on 2023-09-06 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('COMMON_APP', '0048_medicinestocklist'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicinestocklist',
            name='branch',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
