# Generated by Django 4.2.4 on 2023-09-08 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('COMMON_APP', '0050_addvendorstock'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorStockProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='COMMON_APP.stockname')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='COMMON_APP.addvendorstock')),
            ],
        ),
    ]
