# Generated by Django 4.2.4 on 2023-09-08 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('COMMON_APP', '0053_placeorderstock'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=225)),
            ],
        ),
        migrations.AddField(
            model_name='addvendorstock',
            name='vendor_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='COMMON_APP.vendorcategory'),
        ),
    ]
