# Generated by Django 4.2.4 on 2023-09-08 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('COMMON_APP', '0054_vendorcategory_addvendorstock_vendor_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorMedicine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='COMMON_APP.addmedicinehr')),
                ('potency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='COMMON_APP.addpotencyhr')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='COMMON_APP.addvendorstock')),
            ],
        ),
    ]
