# Generated by Django 4.2.4 on 2023-09-08 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('COMMON_APP', '0056_medicinestocklist_vendor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaceOrderMedicine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_quantity', models.IntegerField()),
                ('order_timestamp', models.DateTimeField(auto_now_add=True)),
                ('order_delivery_date', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('medicine_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='COMMON_APP.medicinestocklist')),
            ],
        ),
    ]
