# Generated by Django 3.2.5 on 2023-09-13 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('COMMON_APP', '0057_placeordermedicine'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='upload_stock_bill_image',
            field=models.ImageField(null=True, upload_to='stock/'),
        ),
    ]
