# Generated by Django 3.2.5 on 2023-09-13 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('COMMON_APP', '0058_stock_upload_stock_bill_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicinestocklist',
            name='upload_medicine_bill_image',
            field=models.ImageField(null=True, upload_to='medicine/'),
        ),
    ]
