# Generated by Django 3.2.5 on 2023-09-14 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('COMMON_APP', '0059_medicinestocklist_upload_medicine_bill_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillImageStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_image', models.ImageField(upload_to='stock_bill/')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='COMMON_APP.stock')),
            ],
        ),
    ]
