# Generated by Django 3.2.5 on 2023-09-14 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('COMMON_APP', '0060_billimagestock'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillImageMedicine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_image', models.ImageField(upload_to='medicine_bill/')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='COMMON_APP.medicinestocklist')),
            ],
        ),
    ]
