# Generated by Django 3.2.5 on 2023-09-17 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('COMMON_APP', '0061_billimagemedicine'),
    ]

    operations = [
        migrations.AddField(
            model_name='placeorderstock',
            name='email_placed_flag',
            field=models.BooleanField(default=False),
        ),
    ]
