# Generated by Django 3.2.5 on 2023-09-17 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('COMMON_APP', '0062_placeorderstock_email_placed_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='placeordermedicine',
            name='email_placed_flag',
            field=models.BooleanField(default=False),
        ),
    ]
