# Generated by Django 3.2.5 on 2023-09-20 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('COMMON_APP', '0063_placeordermedicine_email_placed_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='placeorderstock',
            name='order_received_flag',
            field=models.BooleanField(default=False),
        ),
    ]
