# Generated by Django 3.2.5 on 2023-09-23 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('COMMON_APP', '0064_placeorderstock_order_received_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='placeordermedicine',
            name='order_received_flag',
            field=models.BooleanField(default=False),
        ),
    ]
