# Generated by Django 3.2.5 on 2023-09-25 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('COMMON_APP', '0066_placeordermedicine_potency'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaceOrderMedicineNew',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_quantity', models.IntegerField()),
                ('order_timestamp', models.DateField(auto_now_add=True)),
                ('order_delivery_date', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('email_placed_flag', models.BooleanField(default=False)),
                ('order_received_flag', models.BooleanField(default=False)),
                ('medicine_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='COMMON_APP.medicinestocklist')),
                ('potency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='COMMON_APP.addpotencyhr')),
            ],
        ),
    ]
