# Generated by Django 3.2.5 on 2023-09-29 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('COMMON_APP', '0068_placeordermedicine_vendor_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='placeordermedicinenew',
            name='vendor_order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='COMMON_APP.vendormedicine'),
        ),
    ]
