# Generated by Django 3.2.5 on 2023-09-29 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('COMMON_APP', '0070_alter_placeordermedicinenew_vendor_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placeordermedicine',
            name='medicine_order',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='placeordermedicine',
            name='potency',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
