# Generated by Django 3.2.5 on 2023-09-29 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('COMMON_APP', '0071_auto_20230929_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placeordermedicinenew',
            name='medicine_order',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='placeordermedicinenew',
            name='potency',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
