# Generated by Django 3.2.5 on 2023-09-29 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('COMMON_APP', '0072_auto_20230929_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placeordermedicinenew',
            name='medicine_order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='COMMON_APP.medicinestocklist'),
        ),
        migrations.AlterField(
            model_name='placeordermedicinenew',
            name='potency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='COMMON_APP.addpotencyhr'),
        ),
    ]
