# Generated by Django 3.2.5 on 2023-10-02 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('COMMON_APP', '0074_placeordermedicineone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='placeordermedicineone',
            name='vendor_order',
        ),
        migrations.AddField(
            model_name='placeordermedicineone',
            name='vendor_order',
            field=models.ManyToManyField(to='COMMON_APP.AddVendorStock'),
        ),
    ]
