# Generated by Django 3.2.5 on 2023-10-02 18:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('COMMON_APP', '0075_auto_20231002_2330'),
    ]

    operations = [
        migrations.AddField(
            model_name='placeordermedicineone',
            name='order_timestamp',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2023, 10, 2, 18, 28, 35, 768490, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
