# Generated by Django 3.2.5 on 2023-10-04 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('COMMON_APP', '0076_placeordermedicineone_order_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='placeordermedicineone',
            name='order_delivery_date',
            field=models.DateField(null=True),
        ),
    ]
