# Generated by Django 3.2.5 on 2023-10-06 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('COMMON_APP', '0078_placeordermedicineone_order_received_flag'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderMedicineItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_received', models.PositiveIntegerField(default=0)),
                ('order_balance', models.PositiveIntegerField(default=0)),
                ('email_status', models.BooleanField(default=False)),
                ('ordered_med', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='COMMON_APP.placeordermedicineone')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='COMMON_APP.addvendorstock')),
            ],
        ),
    ]
