# Generated by Django 3.2.5 on 2023-10-06 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('COMMON_APP', '0079_ordermedicineitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placeordermedicineone',
            name='vendor_order',
            field=models.ManyToManyField(related_name='vendor_order', to='COMMON_APP.AddVendorStock'),
        ),
    ]
