# Generated by Django 3.2.5 on 2023-10-10 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('COMMON_APP', '0083_ordermedicineitem_bill_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicinestocklist',
            name='order_status',
            field=models.BooleanField(default=True),
        ),
    ]
