# Generated by Django 3.2.5 on 2023-10-10 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('COMMON_APP', '0085_placeordermedicineone_pack'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermedicineitem',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
