# Generated by Django 3.2.5 on 2023-10-13 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('COMMON_APP', '0087_billordermedicineimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermedicineitem',
            name='bill_image',
        ),
        migrations.AlterField(
            model_name='placeordermedicineone',
            name='pack',
            field=models.CharField(choices=[('', ' Select '), ('10 ML', '10 ML'), ('30 ML', '30 ML'), ('100 ML', '100 ML'), ('450 ML', '450 ML')], default='30 ML', max_length=100, null=True),
        ),
    ]
