# Generated by Django 3.2.5 on 2023-10-13 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('COMMON_APP', '0088_auto_20231013_1815'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicinestocklist',
            name='upload_medicine_bill_image',
        ),
        migrations.DeleteModel(
            name='BillImageMedicine',
        ),
    ]
