# Generated by Django 4.2.3 on 2023-10-16 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("COMMON_APP", "0089_auto_20231013_1830"),
    ]

    operations = [
        migrations.CreateModel(
            name="OurPortfolioImages",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("images", models.ImageField(upload_to="images")),
            ],
        ),
    ]
