# Generated by Django 4.2.3 on 2023-10-26 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("COMMON_APP", "0091_forappointmenthomepage"),
    ]

    operations = [
        migrations.CreateModel(
            name="AddItems",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item_name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="AddUnits",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("unit_name", models.CharField(max_length=50)),
            ],
        ),
    ]
