# Generated by Django 4.2.3 on 2023-10-26 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("COMMON_APP", "0093_itemsvendordetails"),
    ]

    operations = [
        migrations.CreateModel(
            name="ItemUnitInventory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField(blank=True, default="0", null=True)),
                ("branch", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "receive_quantity",
                    models.IntegerField(blank=True, default="0", null=True),
                ),
                (
                    "issue_quantity",
                    models.IntegerField(blank=True, default="0", null=True),
                ),
                (
                    "reorder_level",
                    models.IntegerField(blank=True, default="0", null=True),
                ),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("approval_flag_new", models.BooleanField(default=True)),
                ("approval_flag_issue", models.BooleanField(default=False)),
                ("approval_flag_receive", models.BooleanField(default=False)),
                ("is_order_able", models.BooleanField(default=True)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="COMMON_APP.additems",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="COMMON_APP.addunits",
                    ),
                ),
            ],
        ),
    ]
