# Generated by Django 4.2.3 on 2023-10-26 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("COMMON_APP", "0094_itemunitinventory"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlacedOrderItems",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_date", models.DateField(auto_now_add=True)),
                ("expected_delivery_date", models.DateField(blank=True, null=True)),
                ("ordered_quantity", models.PositiveIntegerField()),
                (
                    "order_items",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="COMMON_APP.itemunitinventory",
                    ),
                ),
                ("vendors", models.ManyToManyField(to="COMMON_APP.itemsvendordetails")),
            ],
        ),
        migrations.CreateModel(
            name="ReceiveOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("actual_delivery_date", models.DateField(blank=True, null=True)),
                ("received_quantity", models.PositiveIntegerField(default=0)),
                ("order_balance", models.PositiveIntegerField(default=0)),
                ("order_receive_flag", models.BooleanField(default=False)),
                ("is_approved", models.BooleanField(default=False)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="COMMON_APP.placedorderitems",
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="COMMON_APP.itemsvendordetails",
                    ),
                ),
            ],
        ),
    ]
