# Generated by Django 4.2.3 on 2023-10-26 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("COMMON_APP", "0097_orderitemsbillimage"),
    ]

    operations = [
        migrations.RenameField(
            model_name="orderitemsbillimage",
            old_name="medicine",
            new_name="item",
        ),
    ]
