# Generated by Django 4.2.3 on 2023-10-28 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("COMMON_APP", "0098_rename_medicine_orderitemsbillimage_item"),
    ]

    operations = [
        migrations.CreateModel(
            name="AddMedicineList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("medicine_name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="AddPotencyList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("potency_name", models.CharField(max_length=50)),
            ],
        ),
    ]
