# Generated by Django 4.2.3 on 2023-10-28 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("COMMON_APP", "0099_addmedicinelist_addpotencylist"),
    ]

    operations = [
        migrations.CreateModel(
            name="MedicinesVendorDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vendor_name", models.CharField(max_length=100)),
                ("mobile_number", models.CharField(max_length=10)),
                ("email", models.EmailField(max_length=254)),
                ("address", models.TextField()),
            ],
        ),
    ]
