# Generated by Django 4.2.3 on 2023-10-28 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("COMMON_APP", "0101_medicinepotencystock"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlacedOrderMedicine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_date", models.DateField(auto_now_add=True)),
                ("expected_delivery_date", models.DateField(blank=True, null=True)),
                ("ordered_quantity", models.PositiveIntegerField()),
                ("pack", models.CharField(default="30 ML", max_length=100, null=True)),
                (
                    "order_items",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="COMMON_APP.medicinepotencystock",
                    ),
                ),
                (
                    "vendors",
                    models.ManyToManyField(to="COMMON_APP.medicinesvendordetails"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReceiveOrderMedicine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("actual_delivery_date", models.DateField(blank=True, null=True)),
                ("received_quantity", models.PositiveIntegerField(default=0)),
                ("order_balance", models.PositiveIntegerField(default=0)),
                ("order_receive_flag", models.BooleanField(default=False)),
                ("is_approved", models.BooleanField(default=False)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="COMMON_APP.placedordermedicine",
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="COMMON_APP.medicinesvendordetails",
                    ),
                ),
            ],
        ),
    ]
