# Generated by Django 4.2.3 on 2023-10-29 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("COMMON_APP", "0102_placedordermedicine_receiveordermedicine"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderMedicinesBillImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("images", models.ImageField(upload_to="images")),
                ("receive_timestamp", models.DateField(auto_now_add=True)),
                (
                    "payment_method",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("payment_date", models.DateField(auto_now=True)),
                (
                    "transaction_detail",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("remark", models.TextField(blank=True, null=True)),
                ("image_two", models.ImageField(upload_to="images")),
                (
                    "medicine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="COMMON_APP.receiveordermedicine",
                    ),
                ),
            ],
        ),
    ]
