# Generated by Django 4.2.3 on 2023-10-31 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("COMMON_APP", "0103_ordermedicinesbillimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="placedordermedicine",
            name="added_by",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="receiveordermedicine",
            name="added_by",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
