# Generated by Django 4.2.3 on 2023-10-31 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("COMMON_APP", "0104_placedordermedicine_added_by_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlaceOrderDoctor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_date", models.DateField(auto_now_add=True)),
                ("expected_delivery_date", models.DateField(blank=True, null=True)),
                ("order_medicine", models.CharField(max_length=255)),
                ("potency", models.CharField(max_length=50)),
                ("ordered_quantity", models.PositiveIntegerField()),
                ("pack", models.CharField(default="30 ML", max_length=100, null=True)),
                (
                    "vendors",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="COMMON_APP.medicinesvendordetails",
                    ),
                ),
            ],
        ),
    ]
