# Generated by Django 4.2.3 on 2023-10-31 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("COMMON_APP", "0105_placeorderdoctor"),
    ]

    operations = [
        migrations.AddField(
            model_name="placeorderdoctor",
            name="branch",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
