# Generated by Django 4.2.3 on 2023-11-01 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("COMMON_APP", "0106_placeorderdoctor_branch"),
    ]

    operations = [
        migrations.CreateModel(
            name="HomeoBook",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("medicine_name", models.CharField(max_length=255)),
                ("symptoms", models.TextField()),
                ("timestamp", models.DateField(auto_now=True)),
            ],
        ),
    ]
