# Generated by Django 4.2.3 on 2023-11-01 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("COMMON_APP", "0107_homeobook"),
    ]

    operations = [
        migrations.RenameField(
            model_name="homeobook",
            old_name="symptoms",
            new_name="description",
        ),
    ]
