# Generated by Django 4.2.3 on 2023-11-01 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("COMMON_APP", "0108_rename_symptoms_homeobook_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="placeorderdoctor",
            name="email_status",
            field=models.BooleanField(default=False),
        ),
    ]
