# Generated by Django 4.2.3 on 2023-11-03 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("COMMON_APP", "0110_homebookmedicine_delete_homeobook"),
    ]

    operations = [
        migrations.RenameField(
            model_name="homebookmedicine",
            old_name="name",
            new_name="medicine_name",
        ),
    ]
