# Generated by Django 4.2.3 on 2023-11-03 09:13

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("COMMON_APP", "0112_homebookdisease_delete_placeorderdoctor"),
    ]

    operations = [
        migrations.CreateModel(
            name="HomeBookRedline",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("redline_symptoms", models.CharField(max_length=255)),
                ("description", ckeditor.fields.RichTextField()),
                ("created_date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
