# Generated by Django 4.2.3 on 2023-11-04 18:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("COMMON_APP", "0114_assigntask"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assigntask",
            name="assigned_to",
            field=models.ForeignKey(
                limit_choices_to=models.Q(
                    ("receptionist__isnull", False), ("hr__isnull", False)
                ),
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
