# Generated by Django 4.2.3 on 2023-11-04 18:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("COMMON_APP", "0115_alter_assigntask_assigned_to"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="assigntask",
            name="assigned_to",
        ),
        migrations.AddField(
            model_name="assigntask",
            name="assign_To",
            field=models.ForeignKey(
                limit_choices_to=models.Q(
                    ("receptionist__isnull", False),
                    ("hr__isnull", False),
                    _connector="OR",
                ),
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
