# Generated by Django 4.2.3 on 2023-11-06 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("COMMON_APP", "0116_remove_assigntask_assigned_to_assigntask_assign_to"),
    ]

    operations = [
        migrations.AddField(
            model_name="prescription",
            name="dose",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="prescription",
            name="note",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
