# Generated by Django 4.2.3 on 2023-11-08 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("COMMON_APP", "0117_prescription_dose_prescription_note"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prescription",
            name="note",
            field=models.TextField(blank=True, null=True),
        ),
    ]
