# Generated by Django 4.2.3 on 2023-11-08 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("COMMON_APP", "0119_leaverequest"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="leaverequest",
            name="approved_by",
        ),
    ]
