# Generated by Django 4.2.3 on 2023-11-19 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("COMMON_APP", "0121_leaverequest_duration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prescription",
            name="diagnose",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
