# Generated by Django 4.2.3 on 2023-12-07 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("COMMON_APP", "0122_alter_prescription_diagnose"),
    ]

    operations = [
        migrations.AlterField(
            model_name="otherprescription",
            name="other_price",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
