# Generated by Django 4.2.3 on 2023-12-12 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("COMMON_APP", "0124_alter_otherprescription_other_price"),
    ]

    operations = [
        migrations.CreateModel(
            name="HealthAssessment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bp", models.CharField(max_length=50)),
                ("weight", models.CharField(max_length=10)),
                ("date", models.DateField(auto_now_add=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="COMMON_APP.appointment",
                    ),
                ),
            ],
        ),
    ]
