# Generated by Django 4.1.5 on 2023-01-26 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DOCTER', '0003_examplemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_case', models.IntegerField()),
                ('seven_days', models.IntegerField()),
                ('fifteen_days', models.IntegerField()),
                ('twentyone_days', models.IntegerField()),
                ('thirty_days', models.IntegerField()),
                ('fortyfive_days', models.IntegerField()),
                ('two_months', models.IntegerField()),
                ('three_months', models.IntegerField()),
            ],
        ),
    ]
