# Generated by Django 4.1.5 on 2023-01-27 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PATIENT', '0014_alter_patient_blood'),
        ('DOCTER', '0006_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='amount',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='PATIENT.patient'),
        ),
        migrations.AddField(
            model_name='amount',
            name='transac_id',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='amount',
            name='paid_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
