# Generated by Django 4.1.5 on 2023-01-30 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DOCTER', '0008_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='amount',
            name='balance_flag',
            field=models.BooleanField(default=False),
        ),
    ]
