# Generated by Django 4.1.5 on 2023-02-02 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DOCTER', '0010_amount_cash_amount_amount_online_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddMedicine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('potency', models.CharField(max_length=10)),
                ('quantity', models.IntegerField()),
                ('arrival_date', models.DateField(auto_now=True)),
            ],
        ),
    ]
