# Generated by Django 4.1.5 on 2023-02-03 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PATIENT', '0014_alter_patient_blood'),
        ('DOCTER', '0011_addmedicine'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourierDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courier_amount', models.IntegerField()),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateField(auto_now=True)),
                ('email', models.EmailField(max_length=254)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PATIENT.patient')),
            ],
        ),
    ]
