# Generated by Django 4.1.5 on 2023-02-03 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DOCTER', '0012_courierdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courierdetails',
            name='address',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
