# Generated by Django 4.1.5 on 2023-02-04 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DOCTER', '0013_alter_courierdetails_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='courierdetails',
            name='email_flag',
            field=models.BooleanField(default=False),
        ),
    ]
