# Generated by Django 4.1.5 on 2023-02-09 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DOCTER', '0015_alter_courierdetails_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddStaff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('staff_id', models.IntegerField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_number', models.IntegerField(blank=True, null=True)),
                ('join_date', models.DateField(auto_now=True)),
                ('role', models.CharField(blank=True, max_length=50, null=True)),
                ('branch', models.CharField(blank=True, max_length=100, null=True)),
                ('upload_image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('upload_docs', models.ImageField(blank=True, null=True, upload_to='images')),
            ],
        ),
    ]
