# Generated by Django 4.1.5 on 2023-02-12 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PATIENT', '0015_patient_display_flag'),
        ('DOCTER', '0018_bill'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnose1', models.CharField(blank=True, max_length=100, null=True)),
                ('diagnose2', models.CharField(blank=True, max_length=100, null=True)),
                ('diagnose3', models.CharField(blank=True, max_length=100, null=True)),
                ('date1', models.DateField(blank=True, null=True)),
                ('date2', models.DateField(blank=True, null=True)),
                ('date3', models.DateField(blank=True, null=True)),
                ('date4', models.DateField(blank=True, null=True)),
                ('month', models.IntegerField(blank=True, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PATIENT.patient')),
            ],
        ),
    ]
