# Generated by Django 4.1.5 on 2023-02-15 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DOCTER', '0019_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='date1',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='date2',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
