# Generated by Django 4.2.3 on 2023-08-16 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DOCTER', '0020_bill_date1_bill_date2'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosis',
            name='med_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
