# Generated by Django 4.2.3 on 2023-08-25 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DOCTER', '0021_diagnosis_med_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='docter',
            name='forget_password_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
