# Generated by Django 4.2.3 on 2023-11-26 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("DOCTER", "0022_docter_forget_password_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="courierdetails",
            name="receiver_flag",
            field=models.BooleanField(default=False),
        ),
    ]
