# Generated by Django 4.2.3 on 2023-11-26 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("DOCTER", "0023_courierdetails_receiver_flag"),
    ]

    operations = [
        migrations.AlterField(
            model_name="courierdetails",
            name="date",
            field=models.DateField(auto_now_add=True),
        ),
    ]
