# Generated by Django 4.2.3 on 2023-11-27 18:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("DOCTER", "0024_alter_courierdetails_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="balance",
            name="bal_date",
            field=models.DateField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
