# Generated by Django 4.2.3 on 2023-11-27 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("DOCTER", "0025_balance_bal_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="balance",
            name="bal_date",
        ),
        migrations.AlterField(
            model_name="balance",
            name="previous_deal_date",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
