# Generated by Django 4.2.3 on 2023-11-27 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("DOCTER", "0027_alter_balance_previous_deal_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="courierdetails",
            name="balance_amount",
            field=models.IntegerField(default=0),
        ),
    ]
