# Generated by Django 4.2.3 on 2023-11-27 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("DOCTER", "0028_courierdetails_balance_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="courierdetails",
            name="paid_amount",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="courierdetails",
            name="paid_on",
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name="courierdetails",
            name="transaction_id",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
