# Generated by Django 4.2.3 on 2023-11-29 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("DOCTER", "0029_courierdetails_paid_amount_courierdetails_paid_on_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="balance",
            name="previous_deal_date",
            field=models.DateField(auto_now=True),
        ),
    ]
