# Generated by Django 4.2.3 on 2023-12-05 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("DOCTER", "0031_amount_collected_by_balance_collected_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="courierdetails",
            name="collected_by",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
