# Generated by Django 4.2.3 on 2023-12-08 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("DOCTER", "0032_courierdetails_collected_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="courierdetails",
            name="collected_by",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
