# Generated by Django 4.2.3 on 2024-01-23 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0039_alter_presentcomplaintsnew_complain"),
        ("PATIENT", "0025_patient_diagnosis_final_and_more"),
        ("DOCTER", "0033_alter_courierdetails_collected_by"),
    ]

    operations = [
        migrations.CreateModel(
            name="DiagnosisNew",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("med_name", models.CharField(blank=True, max_length=100, null=True)),
                ("date", models.DateField(auto_now=True)),
                (
                    "diagnose",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.presentcomplaintsnew",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="PATIENT.patient",
                    ),
                ),
            ],
        ),
    ]
