# Generated by Django 4.1.1 on 2022-11-25 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_question_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appetite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=500)),
                ('question', models.TextField()),
            ],
        ),
    ]
