# Generated by Django 4.1.1 on 2022-12-06 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_qanswar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qanswar',
            name='answars',
            field=models.TextField(blank=True, null=True),
        ),
    ]
