# Generated by Django 4.1.1 on 2022-12-20 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_qanswar_answars'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answars', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
