# Generated by Django 4.1.5 on 2023-02-27 12:37

from django.db import migrations, models
import django.db.models.deletion
import jsignature.fields


class Migration(migrations.Migration):

    dependencies = [
        ('PATIENT', '0015_patient_display_flag'),
        ('dashboard', '0010_alter_answer_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExampleModel1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signature', jsignature.fields.JSignatureField(blank=True, null=True, verbose_name='Signature')),
                ('signature_date', models.DateTimeField(blank=True, null=True, verbose_name='Signature date')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='PATIENT.patient')),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.question')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
