# Generated by Django 4.1.5 on 2023-02-27 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PATIENT', '0015_patient_display_flag'),
        ('dashboard', '0011_examplemodel1'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExampleModel1',
            new_name='JSModel',
        ),
    ]
