# Generated by Django 4.1.5 on 2023-02-27 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_rename_examplemodel1_jsmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jsmodel',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.question1'),
        ),
    ]
