# Generated by Django 4.1.5 on 2023-03-03 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PATIENT', '0015_patient_display_flag'),
        ('dashboard', '0013_alter_jsmodel_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalHabit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weather_hot', models.CharField(blank=True, max_length=50, null=True)),
                ('weather_cold', models.CharField(blank=True, max_length=50, null=True)),
                ('weather_rainy', models.CharField(blank=True, max_length=50, null=True)),
                ('weather_humid', models.CharField(blank=True, max_length=50, null=True)),
                ('weather_dry', models.CharField(blank=True, max_length=50, null=True)),
                ('getting_wet', models.CharField(blank=True, max_length=50, null=True)),
                ('weather_open_air', models.CharField(blank=True, max_length=50, null=True)),
                ('weather_wind', models.CharField(blank=True, max_length=50, null=True)),
                ('weather_seashore', models.CharField(blank=True, max_length=50, null=True)),
                ('weather_noise', models.CharField(blank=True, max_length=50, null=True)),
                ('weather_light', models.CharField(blank=True, max_length=50, null=True)),
                ('weather_strong_smell', models.CharField(blank=True, max_length=50, null=True)),
                ('weather_dust', models.CharField(blank=True, max_length=50, null=True)),
                ('weather_smoke', models.CharField(blank=True, max_length=50, null=True)),
                ('weather_before', models.CharField(blank=True, max_length=50, null=True)),
                ('weather_during', models.CharField(blank=True, max_length=50, null=True)),
                ('weather_after_period', models.CharField(blank=True, max_length=50, null=True)),
                ('weather_touch', models.CharField(blank=True, max_length=50, null=True)),
                ('weather_massage', models.CharField(blank=True, max_length=50, null=True)),
                ('weather_pressure', models.CharField(blank=True, max_length=50, null=True)),
                ('weather_small_closed_place', models.CharField(blank=True, max_length=50, null=True)),
                ('weather_crowds', models.CharField(blank=True, max_length=50, null=True)),
                ('weather_tight_clothes', models.CharField(blank=True, max_length=50, null=True)),
                ('weather_exams', models.CharField(blank=True, max_length=50, null=True)),
                ('weather_interview', models.CharField(blank=True, max_length=50, null=True)),
                ('weather_appointment', models.CharField(blank=True, max_length=50, null=True)),
                ('weather_exercise', models.CharField(blank=True, max_length=50, null=True)),
                ('weather_exertion', models.CharField(blank=True, max_length=50, null=True)),
                ('weather_walk', models.CharField(blank=True, max_length=50, null=True)),
                ('weather_running', models.CharField(blank=True, max_length=50, null=True)),
                ('weather_full_moon', models.CharField(blank=True, max_length=50, null=True)),
                ('weather_new_moon', models.CharField(blank=True, max_length=50, null=True)),
                ('weather_sun', models.CharField(blank=True, max_length=50, null=True)),
                ('weather_change', models.CharField(blank=True, max_length=50, null=True)),
                ('date', models.DateField(auto_now=True, null=True)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='PATIENT.patient')),
            ],
        ),
    ]
