# Generated by Django 4.1.5 on 2023-03-03 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PATIENT', '0015_patient_display_flag'),
        ('dashboard', '0014_personalhabit'),
    ]

    operations = [
        migrations.CreateModel(
            name='InFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sweet', models.CharField(blank=True, max_length=50, null=True)),
                ('bitter', models.CharField(blank=True, max_length=50, null=True)),
                ('bread', models.CharField(blank=True, max_length=50, null=True)),
                ('eggs', models.CharField(blank=True, max_length=50, null=True)),
                ('cold_drinks', models.CharField(blank=True, max_length=50, null=True)),
                ('chocolates', models.CharField(blank=True, max_length=50, null=True)),
                ('mud_chalk_paper', models.CharField(blank=True, max_length=50, null=True)),
                ('salt', models.CharField(blank=True, max_length=50, null=True)),
                ('fat', models.CharField(blank=True, max_length=50, null=True)),
                ('butter', models.CharField(blank=True, max_length=50, null=True)),
                ('meat', models.CharField(blank=True, max_length=50, null=True)),
                ('warm_food_drinks', models.CharField(blank=True, max_length=50, null=True)),
                ('fruits', models.CharField(blank=True, max_length=50, null=True)),
                ('pan', models.CharField(blank=True, max_length=50, null=True)),
                ('sour', models.CharField(blank=True, max_length=50, null=True)),
                ('raw_salad', models.CharField(blank=True, max_length=50, null=True)),
                ('snack', models.CharField(blank=True, max_length=50, null=True)),
                ('fish', models.CharField(blank=True, max_length=50, null=True)),
                ('juice', models.CharField(blank=True, max_length=50, null=True)),
                ('ice_cream', models.CharField(blank=True, max_length=50, null=True)),
                ('spicy', models.CharField(blank=True, max_length=50, null=True)),
                ('vegetables', models.CharField(blank=True, max_length=50, null=True)),
                ('cheese', models.CharField(blank=True, max_length=50, null=True)),
                ('onions', models.CharField(blank=True, max_length=50, null=True)),
                ('garlic', models.CharField(blank=True, max_length=50, null=True)),
                ('milk', models.CharField(blank=True, max_length=50, null=True)),
                ('alcohol', models.CharField(blank=True, max_length=50, null=True)),
                ('smoking', models.CharField(blank=True, max_length=50, null=True)),
                ('any_other', models.CharField(blank=True, max_length=50, null=True)),
                ('date', models.DateField(auto_now=True)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='PATIENT.patient')),
            ],
        ),
    ]
