# Generated by Django 4.1.5 on 2023-03-04 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_infood'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infood',
            name='date',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
