# Generated by Django 4.1.5 on 2023-03-08 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PATIENT', '0015_patient_display_flag'),
        ('dashboard', '0018_personalitycharacter'),
    ]

    operations = [
        migrations.CreateModel(
            name='MiasmOne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('psora', models.CharField(blank=True, max_length=50, null=True)),
                ('sycosis', models.CharField(blank=True, max_length=50, null=True)),
                ('syphilis', models.CharField(blank=True, max_length=50, null=True)),
                ('tubercular', models.CharField(blank=True, max_length=50, null=True)),
                ('psora_sycosis', models.CharField(blank=True, max_length=50, null=True)),
                ('psora_syphilis', models.CharField(blank=True, max_length=50, null=True)),
                ('date', models.DateField(auto_now=True)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='PATIENT.patient')),
            ],
        ),
    ]
