# Generated by Django 4.1.7 on 2023-06-08 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PATIENT', '0015_patient_display_flag'),
        ('dashboard', '0021_diseases_pasthistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalHabitNew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desire', models.CharField(blank=True, max_length=50, null=True)),
                ('aversion', models.CharField(blank=True, max_length=50, null=True)),
                ('appetite', models.CharField(blank=True, max_length=50, null=True)),
                ('thirst', models.CharField(blank=True, max_length=50, null=True)),
                ('stool', models.CharField(blank=True, max_length=50, null=True)),
                ('urine', models.CharField(blank=True, max_length=50, null=True)),
                ('sleep', models.CharField(blank=True, max_length=50, null=True)),
                ('dreams', models.CharField(blank=True, max_length=50, null=True)),
                ('date', models.DateField(auto_now=True, null=True)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='PATIENT.patient')),
            ],
        ),
    ]
