# Generated by Django 4.1.6 on 2023-07-02 19:32

from django.db import migrations, models
import django.db.models.deletion
import jsignature.fields


class Migration(migrations.Migration):

    dependencies = [
        ('PATIENT', '0017_newcasepaperupload'),
        ('dashboard', '0024_pasthistorynew'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewCaseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signature', jsignature.fields.JSignatureField(blank=True, null=True, verbose_name='Signature')),
                ('signature_date', models.DateTimeField(blank=True, null=True, verbose_name='Signature date')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.category')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='PATIENT.patient')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
