# Generated by Django 4.1.6 on 2023-07-04 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0026_familymedicalhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='MentalCausativeNewone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
