# Generated by Django 4.1.6 on 2023-07-04 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PATIENT', '0017_newcasepaperupload'),
        ('dashboard', '0027_mentalcausativenewone'),
    ]

    operations = [
        migrations.CreateModel(
            name='MentalCausativeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factors', models.CharField(blank=True, max_length=500, null=True)),
                ('date', models.DateField(auto_now=True)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='PATIENT.patient')),
            ],
        ),
    ]
