# Generated by Django 4.2.3 on 2023-07-23 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0033_miasmnewone_miasmrecords'),
    ]

    operations = [
        migrations.AddField(
            model_name='patienthistorynew',
            name='last_diagnosed',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='patienthistorynew',
            name='last_suffix',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
