# Generated by Django 4.2.3 on 2023-08-04 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0036_medicinestock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicinestock',
            old_name='timestamp',
            new_name='arrival_date',
        ),
    ]
