# Generated by Django 4.2.3 on 2023-08-15 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0037_rename_timestamp_medicinestock_arrival_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presentcomplaintsnew',
            name='complain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard.complain'),
        ),
    ]
