# Generated by Django 4.2.3 on 2023-08-15 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0038_alter_presentcomplaintsnew_complain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presentcomplaintsnew',
            name='complain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.complain'),
        ),
    ]
